### PR TITLE
Fix OCI service cache issue. Closes #258

### LINKED ISSUE #258: Fix OCI service cache issue.
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by bigdatasourav**

### CODE REVIEW

File: oci/service.go [hunk 1]
```diff
@@ -934,7 +934,7 @@ func budgetService(ctx context.Context, d *plugin.QueryData, region string) (*se
 // monitoringService returns the service client for OCI Monitoring Service
 func monitoringService(ctx context.Context, d *plugin.QueryData, region string) (*session, error) {
 	logger := plugin.Logger(ctx)
-	serviceCacheKey := fmt.Sprintf("metric explorer-%s", "region")
+	serviceCacheKey := fmt.Sprintf("monitoring-%s", "region")
```
Comment (Subhajit97) [inline oci/service.go:937]: @bigdatasourav For the other service we have used the serviceCacheKey as `FunctionsManagement`, `IdentityRegional`.
Should we update it to `Monitoring`?
How we decide the serviceCacheKey currently?

Comment (Subhajit97) [inline oci/service.go:937]:
```suggestion
	serviceCacheKey := fmt.Sprintf("Monitoring-%s", "region")
```

**Review by Subhajit97 — APPROVED** [review]
