### PR TITLE
Column delivery_policy does not populate data in get API call in oci_ons_subscription table closes #369

### LINKED ISSUE #369: Column delivery_policy does not populate data in get API call in oci_ons_subscription table
**Describe the bug**
Column delivery_policy does not populate data in get API call in oci_ons_subscription table, where as in list API call it returns information.
```
> select id,delivery_policy from oci_ons_subscription where id = 'ocid1.onssubscription.oc1.iad.aaaaaaaaulkqqxuwm7owqzvc7fwzwuobrgralx3sn4lel4v4qk4pcg7fczgq'
+--------------------------------------------------------------------------------------------+-----------------+
| id                                                                                         | delivery_policy |
+--------------------------------------------------------------------------------------------+-----------------+
| ocid1.onssubscription.oc1.iad.aaaaaaaaulkqqxuwm7owqzvc7fwzwuobrgralx3sn4lel4v4qk4pcg7fczgq | <null>          |
+--------------------------------------------------------------------------------------------+-----------------+
> select id,delivery_policy from oci_ons_subscription
+--------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| id                                                                                         | delivery_policy                                                                |
+--------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| ocid1.onssubscription.oc1.iad.aaaaaaaaulkqqxuwm7owqzvc7fwzwuobrgralx3sn4lel4v4qk4pcg7fczgq | {"backoffRetryPolicy":{"maxRetryDuration":7200000,"policyType":"EXPONENTIAL"}} |
+--------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
Outputs:

created_time = "1699999948386"
endpoint = "test@gmail.com"
etag = "a0d6da2f"
lifecycle_state = "PENDING"
protocol = "EMAIL"
region = "ap-mumbai-1"
resource_id = "ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaa2cndwk1699999948386qw4wxtterdpfz1699999948386uha"
resource_name = "steampipetest8218"
tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaahnm7gleh5so1699999948386po3hoz4p4h21699999948386q"

Running SQL query: test-get-query.sql

[
  {
    "endpoint": "test@gmail.com",
    "etag": "a0d6da2f",
    "freeform_tags": {
      "Name": "steampipetest8218"
    },
    "id": "ocid1.onssubscription.oc1.ap-mumbai-1.aaaaa1699999948386v2ck37gqw4wx1699999948386u43uhuha",
    "protocol": "EMAIL"
  }
]
✔ PASSED

Running SQL query: test-list-query.sql

[
  {
    "endpoint": "test@gmail.com",
    "freeform_tags": {
      "Name": "steampipetest8218"
    },
    "id": "ocid1.onssubscription.oc1.ap-mumbai-1.aaaaaaaa21699999948386gqw4wxtterdpfzho1699999948386ha",
    "lifecycle_state": "PENDING",
    "protocol": "EMAIL"
  }
]
✔ PASSED

Running SQL query: test-not-found-query.sql

null
✔ PASSED

Running SQL query: test-turbot-query.sql

[
  {
    "region": "ap-mumbai-1",
    "tenant_id": "ocid1.tenancy.oc1..aaaaaaa21699999948386gqw4wxtterdpfzho1699999948386ha"
  }
]
✔ PASSED

POSTTEST: tests/oci_ons_subscription

TEARDOWN: tests/oci_ons_subscription

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select id , delivery_policy from oci_ons_subscription
+----------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| id                                                                                                 | delivery_policy                                                                |
+----------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| ocid1.onssubscription.oc1.ap-mumbai-1.aaaaa667fjskjfkjdfuhjssnnsjhd6ilo7vacfb5heywi3pq7nfgsjdfj | {"backoffRetryPolicy":{"maxRetryDuration":7200000,"policyType":"EXPONENTIAL"}} |
+----------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
> select id , delivery_policy from oci_ons_subscription where id = 'ocid1.onssubscription.oc1.ap-mumbai-1.aaaaa667fjskjfkjdfuhjssnnsjhd6ilo7vacfb5heywi3pq7nfgsjdfj'
+----------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| id                                                                                                 | delivery_policy                                                                |
+----------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
| ocid1.onssubscription.oc1.ap-mumbai-1.aaaaa667fjskjfkjdfuhjssnnsjhd6ilo7vacfb5heywi3pq7nfgsjdfj | {"backoffRetryPolicy":{"maxRetryDuration":7200000,"policyType":"EXPONENTIAL"}} |
+----------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------+
```
</details>

### CODE REVIEW

**Comment by ParthaI** [comment]
We are not getting `DeliveryPolicy` details from [get call](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/ons#NotificationDataPlaneClient.GetSubscription) but we are getting these details from [list call ](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/ons#NotificationDataPlaneClient.ListSubscriptions).

File: oci/table_oci_ons_subscription.go [hunk 1]
```diff
@@ -18,13 +17,9 @@ func tableOnsSubscription(_ context.Context) *plugin.Table {
 	return &plugin.Table{
 		Name:        "oci_ons_subscription",
 		Description: "OCI Ons Subscription",
```
Comment (misraved) [inline oci/table_oci_ons_subscription.go:19]:
```suggestion
		Description: "OCI ONS Subscription",
```

**Review by rajlearner17 — APPROVED** [review]
Looks good as per testing

**Comment by cbruno10** [comment]
@khushboo9024 Can you please check if the OCI CLI has the same bug, e.g., getting a specific ONS subscription produces the same error of not getting the delivery policy? If the bug is just in the Go SDK, we should raise a bug report with them, but if it's something in the API, then we should raise an OCI support request.

And as for removing the `GetConfig`, I think that's losing some functionality in this table unnecessarily. If a user runs a query to get a specific subscription and selects all columns from this table except for `delivery_policy`, the Get call is more optimal in this situation. We'd only need to call the List function if they select the `delivery_policy` column (at least from what I can see).

So instead of just removing the `GetConfig`, we should leave it in and update the `delivery_policy` column to hydrate as required.

**Comment by khushboo9024** [comment]
@cbruno10  I checked in OCI CLI ,it works fine, we don't have any bug there. We probably need to raise bug with Go SDK.

**Comment by cbruno10** [comment]
Thanks @khushboo9024 for checking, here's my suggestion:
- We should raise an issue in the OCI Go SDK asking them if this is a bug or intentional
- In this table, we should add a hydrate function for the `delivery_policy` column:
  - If we're coming from the List call, return the delivery policy directly, since the List call response contains it
  - If we're coming from the Get call, call the list subscriptions API, passing in the topic ID from the item, and then returning just the delivery policy from the response for the particular subscription (based on the `id` get qual)

File: oci/table_oci_ons_subscription.go [hunk 2]
```diff
@@ -243,6 +246,81 @@ func getOnsSubscription(ctx context.Context, d *plugin.QueryData, h *plugin.Hydr
 	return response.Subscription, nil
 }
 
+// This hydrate function is to get delivery policy column
+// In case of list call it just return delivery policy without doing any extra api call as list call  contains delivery policy data
+// In case of get call it calls extra list api using topicId as filer to get delivery policy data from the list call
+func getSubscriptionDeliveryPolicy(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
+	plugin.Logger(ctx).Debug("getSubscriptionDeliveryPolicy")
+	logger := plugin.Logger(ctx)
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:254]:
```suggestion
	logger := plugin.Logger(ctx)
	logger..Debug("getSubscriptionDeliveryPolicy")
```

File: oci/table_oci_ons_subscription.go [hunk 3]
```diff
@@ -243,6 +246,81 @@ func getOnsSubscription(ctx context.Context, d *plugin.QueryData, h *plugin.Hydr
...
+	region := plugin.GetMatrixItem(ctx)[matrixKeyRegion].(string)
+	compartment := plugin.GetMatrixItem(ctx)[matrixKeyCompartment].(string)
+	logger.Debug("oci.getOnsSubscription", "Compartment", compartment, "OCI_REGION", region)
+
+	policy := deliveryPolicy(ctx, h.Item)
+
+	if policy != nil {
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:261]:
```suggestion
	// If the subscription is from the list call, we already have the policy
	if policy != nil {
```

File: oci/table_oci_ons_subscription.go [hunk 4]
```diff
@@ -243,6 +246,81 @@ func getOnsSubscription(ctx context.Context, d *plugin.QueryData, h *plugin.Hydr
...
+		return nil, nil
+	}
+
+	// Create Session
+	session, err := onsNotificationDataPlaneService(ctx, d, region)
+	if err != nil {
+		return nil, err
+	}
+
+	get := h.Item.(ons.Subscription)
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:278]:
```suggestion
	subscriptionItem := h.Item.(ons.Subscription)
```

File: oci/table_oci_ons_subscription.go [hunk 5]
```diff
@@ -243,6 +246,81 @@ func getOnsSubscription(ctx context.Context, d *plugin.QueryData, h *plugin.Hydr
...
+	request := ons.ListSubscriptionsRequest{
+		CompartmentId: types.String(compartment),
+		TopicId:       types.String(*get.TopicId),
+		Limit:         types.Int(50),
+		RequestMetadata: common.RequestMetadata{
+			RetryPolicy: getDefaultRetryPolicy(d.Connection),
+		},
+	}
+
+	// Check for additional filter
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:288]: Do we want to check for limits? I don't think we need to since we know that the limit doesn't matter here, since we're just getting 1 subscription's delivery policy and we need to check all subscriptions for the topic anyway

File: oci/table_oci_ons_subscription.go [hunk 6]
```diff
@@ -243,6 +246,81 @@ func getOnsSubscription(ctx context.Context, d *plugin.QueryData, h *plugin.Hydr
...
+			}
+		}
+		if response.OpcNextPage != nil {
+			request.Page = response.OpcNextPage
+		} else {
+			pagesLeft = false
+		}
+	}
+
+	return nil, nil
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:320]: When would we hit this case, is it possible?

File: oci/table_oci_ons_subscription.go [hunk 7]
```diff
@@ -243,6 +246,81 @@ func getOnsSubscription(ctx context.Context, d *plugin.QueryData, h *plugin.Hydr
 	return response.Subscription, nil
 }
 
+// This hydrate function is to get delivery policy column
+// In case of list call it just return delivery policy without doing any extra api call as list call  contains delivery policy data
+// In case of get call it calls extra list api using topicId as filer to get delivery policy data from the list call
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:251]:
```suggestion
/*
The delivery policy is returned in the list, but not get the call (https://github.com/turbot/steampipe-plugin-oci/issues/369).
So if we're hydrated from the list call, return the delivery policy directly,
but if we're hydrated from the get call, we need to make an extra list call and
filter on the topic ID.
*/
```

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@khushboo9024 Can you please raise an issue in https://github.com/oracle/oci-go-sdk/issues and link to it in https://github.com/turbot/steampipe-plugin-oci/issues/369?

Also, please see review comments, thanks!

File: oci/table_oci_ons_subscription.go [hunk 8]
```diff
@@ -275,25 +280,15 @@ func getSubscriptionDeliveryPolicy(ctx context.Context, d *plugin.QueryData, h *
 		return nil, err
 	}
 
-	get := h.Item.(ons.Subscription)
+	subscriptionItem := h.Item.(ons.Subscription)
 	request := ons.ListSubscriptionsRequest{
 		CompartmentId: types.String(compartment),
-		TopicId:       types.String(*get.TopicId),
-		Limit:         types.Int(50),
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go]: What is the default `Limit`? I think it's ok to leave a Limit here, my review comment was primarily around not respecting the SQL query `limit`

File: oci/table_oci_ons_subscription.go [hunk 9]
```diff
@@ -317,7 +312,7 @@ func getSubscriptionDeliveryPolicy(ctx context.Context, d *plugin.QueryData, h *
 		}
 	}
 
-	return nil, nil
+	return nil, err
```
Comment (cbruno10) [inline oci/table_oci_ons_subscription.go:315]: I still don't quite get if we'd ever hit this `return` statement, I think we may need it, but would we hit here if we couldn't find the subscription from the topic's list of subscriptions?

Comment (khushboo9024) [reply oci/table_oci_ons_subscription.go:316]: Yes agree we will not hit this condition, but we need it.

**Review by cbruno10 — APPROVED** [review]
